### PR TITLE
add stl for m12 lens mount

### PR DESCRIPTION
**Pull request by whoim2**
for cameras

### CODE REVIEW

**Comment by flyrouter** [comment]
Please post all your 3D models on printables and don't forget to put those #openIPC to make your work visible on this link - https://www.printables.com/search/models?q=tag:openipc

**Review by flyrouter — CHANGES_REQUESTED** [review]
Please post all your 3D models on printables and don't forget to put those #openIPC to make your work visible on this link - https://www.printables.com/search/models?q=tag:openipc

**Comment by whoim2** [comment]
Its not my model, im find this in google and post link to chat. Mario says: publish in hardware.

**Comment by flyrouter** [comment]
We only publish electronic boards here

**Pull request closed without merging**
