### PR TITLE
add 3D model for NVR board

### PR DESCRIPTION
**Pull request by KennyPlus**

### CODE REVIEW

**Comment by flyrouter** [comment]
Please post all your 3D models on printables and don't forget to put those #openIPC to make your work visible on this link - https://www.printables.com/search/models?q=tag:openipc

**Review by flyrouter — CHANGES_REQUESTED** [review]
Please post all your 3D models on printables and don't forget to put those #openIPC to make your work visible on this link - https://www.printables.com/search/models?q=tag:openipc

**Comment by KennyPlus** [comment]
[add flash type convert for camhi and anjoy]

**Comment by KennyPlus** [comment]
> Please post all your 3D models on printables and don't forget to put those #openIPC to make your work visible on this link - https://www.printables.com/search/models?q=tag:openipc

OK

**Pull request closed without merging**
